### ISSUE TITLE
what does the n_sample mean? 

### ISSUE THREAD

**Issue by IronLavender** [mori97/VaDE#1]
Thanks for your work! And I have a question, in vade.py, what does the _n_sample_ mean? 
`def classify(self, x, n_samples=8)`

**Comment by mori97** [comment]
I'm sorry for the late reply.
The `n_sample` means the number of samples obtained by the reparameterization trick from the estimated variational mean (mu) and the standard deviation (0.5 * logvar.exp()).

**Comment by sherlock1987** [comment]
Is n_sample the larger, the better?
